

--Criando tabela FUNCIONARIOS (Resolução do exercício 8 da semana 7).OBS.:TABELA NÃO NORMALIZADA
CREATE TABLE FUNCIONARIOS(
ID INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50)NOT NULL,
CARGO VARCHAR(50)NOT NULL,
TELEFONE1 VARCHAR(50)NOT NULL,
TELEFONE2 VARCHAR(50)NOT NULL
);

SET IDENTITY_INSERT FUNCIONARIOS ON

INSERT INTO FUNCIONARIOS(ID,NOME,CARGO,TELEFONE1,TELEFONE2) VALUES ('1','Marcos','Atendente','3654589','36545987')
INSERT INTO FUNCIONARIOS(ID,NOME,CARGO,TELEFONE1,TELEFONE2) VALUES ('2','Maria','Gerente','36524569','36524569')
INSERT INTO FUNCIONARIOS(ID,NOME,CARGO,TELEFONE1,TELEFONE2) VALUES ('3','Julia','Atendente','3654962','12365458')

SET IDENTITY_INSERT FUNCIONARIOS OFF


DROP TABLE FUNCIONARIOS--APAGAR TABELA FUNCIONARIOS NÃO NORMALIZADA


	
-----------------------------------------
--PRIMEIRA FORMA DE NORMALIZAÇÃO 1FN
CREATE TABLE FUNCIONARIO(ID INT PRIMARY KEY,NOME VARCHAR(50),CARGO VARCHAR(50));

CREATE TABLE TELEFONE(ID INT REFERENCES FUNCIONARIO(ID) NOT NULL ,TELEFONE VARCHAR(11) NOT NULL );

ALTER TABLE TELEFONE ADD PRIMARY KEY (ID, TELEFONE)

DROP TABLE FUNCIONARIO---APAGAR TABELA FUNCIONARIO

-----------------------------------------------------------
---TERCEIRA FORMA DE NORMALIZAÇÃO 3NF
CREATE TABLE CARGO(ID INT IDENTITY (1,1) PRIMARY KEY, CARGO VARCHAR(50));

CREATE TABLE FUNCIONARIO(ID INT PRIMARY KEY,NOME VARCHAR(50),CARGO_ID INT REFERENCES CARGO(ID));

CREATE TABLE TELEFONE(ID INT REFERENCES FUNCIONARIO(ID) NOT NULL ,TELEFONE VARCHAR(11) NOT NULL );

ALTER TABLE TELEFONE ADD PRIMARY KEY (ID, TELEFONE)

CREATE TABLE TELEFONE2(ID INT REFERENCES FUNCIONARIO(ID) NOT NULL ,TELEFONE VARCHAR(11) NOT NULL );

ALTER TABLE TELEFONE2 ADD PRIMARY KEY (ID, TELEFONE)

INSERT INTO CARGO VALUES ('Atendente'),('Gerente'),('Atendente')
INSERT INTO FUNCIONARIO VALUES (1, 'Marcos', 1),(2, 'Maria', 2),(3, 'Julia', 3)
INSERT INTO TELEFONE VALUES (1, '3654589'),(2, '3654698'), (3, '3654962')
INSERT INTO TELEFONE2 VALUES (1, '36545987'),(2, '36524569'), (3, '12365458')

SELECT*FROM FUNCIONARIO
SELECT*FROM CARGO
SELECT*FROM TELEFONE
SELECT*FROM TELEFONE2

